// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vekuvhkccmfdtzhgomzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZla3V2aGtjY21mZHR6aGdvbXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTM0MDMsImV4cCI6MjA2MDk4OTQwM30.b_ePH-lyDeRmSCoTvYpgWTd-SCez1GllyRPRzqPSARg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);